-- VHDL netlist generated by SCUBA ispLever_v8.1_PROD_Build (20)
-- Module  Version: 3.5
--C:\ispTOOLS8_1\ispfpga\bin\nt\scuba.exe -w -lang vhdl -synth synplify -bus_exp 7 -bb -arch mj5g00 -type sdpram -rdata_width 8 -data_width 8 -num_rows 128 -outData REGISTERED -e 

-- Thu Dec 09 18:21:17 2010

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO;
use MACHXO.components.all;
-- synopsys translate_on

entity DPRAM is
    port (
        WrAddress: in  std_logic_vector(6 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        WrClock: in  std_logic; 
        WE: in  std_logic; 
        WrClockEn: in  std_logic; 
        RdAddress: in  std_logic_vector(6 downto 0); 
        RdClock: in  std_logic; 
        RdClockEn: in  std_logic; 
        Reset: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0));
end DPRAM;

architecture Structure of DPRAM is

    -- internal signal declarations
    signal func_and_inet: std_logic;
    signal func_and_inet_1: std_logic;
    signal func_and_inet_2: std_logic;
    signal waddr6_inv: std_logic;
    signal func_and_inet_3: std_logic;
    signal func_and_inet_4: std_logic;
    signal waddr5_inv: std_logic;
    signal func_and_inet_5: std_logic;
    signal waddr4_inv: std_logic;
    signal func_and_inet_6: std_logic;
    signal scuba_vhi: std_logic;
    signal func_and_inet_7: std_logic;
    signal dataout7_ffin: std_logic;
    signal dataout6_ffin: std_logic;
    signal dataout5_ffin: std_logic;
    signal dataout4_ffin: std_logic;
    signal dataout3_ffin: std_logic;
    signal dataout2_ffin: std_logic;
    signal dataout1_ffin: std_logic;
    signal dataout0_ffin: std_logic;
    signal mdL0_0_0: std_logic;
    signal mdL0_0_1: std_logic;
    signal mdL0_0_2: std_logic;
    signal mdL0_0_3: std_logic;
    signal mdL0_0_4: std_logic;
    signal mdL0_0_5: std_logic;
    signal mdL0_0_6: std_logic;
    signal mdL0_0_7: std_logic;
    signal dec0_wre3: std_logic;
    signal mdL0_1_0: std_logic;
    signal mdL0_1_1: std_logic;
    signal mdL0_1_2: std_logic;
    signal mdL0_1_3: std_logic;
    signal mdL0_1_4: std_logic;
    signal mdL0_1_5: std_logic;
    signal mdL0_1_6: std_logic;
    signal mdL0_1_7: std_logic;
    signal dec1_wre7: std_logic;
    signal mdL0_2_0: std_logic;
    signal mdL0_2_1: std_logic;
    signal mdL0_2_2: std_logic;
    signal mdL0_2_3: std_logic;
    signal mdL0_2_4: std_logic;
    signal mdL0_2_5: std_logic;
    signal mdL0_2_6: std_logic;
    signal mdL0_2_7: std_logic;
    signal dec2_wre11: std_logic;
    signal mdL0_3_0: std_logic;
    signal mdL0_3_1: std_logic;
    signal mdL0_3_2: std_logic;
    signal mdL0_3_3: std_logic;
    signal mdL0_3_4: std_logic;
    signal mdL0_3_5: std_logic;
    signal mdL0_3_6: std_logic;
    signal mdL0_3_7: std_logic;
    signal dec3_wre15: std_logic;
    signal mdL0_4_0: std_logic;
    signal mdL0_4_1: std_logic;
    signal mdL0_4_2: std_logic;
    signal mdL0_4_3: std_logic;
    signal mdL0_4_4: std_logic;
    signal mdL0_4_5: std_logic;
    signal mdL0_4_6: std_logic;
    signal mdL0_4_7: std_logic;
    signal dec4_wre19: std_logic;
    signal mdL0_5_0: std_logic;
    signal mdL0_5_1: std_logic;
    signal mdL0_5_2: std_logic;
    signal mdL0_5_3: std_logic;
    signal mdL0_5_4: std_logic;
    signal mdL0_5_5: std_logic;
    signal mdL0_5_6: std_logic;
    signal mdL0_5_7: std_logic;
    signal dec5_wre23: std_logic;
    signal mdL0_6_0: std_logic;
    signal mdL0_6_1: std_logic;
    signal mdL0_6_2: std_logic;
    signal mdL0_6_3: std_logic;
    signal mdL0_6_4: std_logic;
    signal mdL0_6_5: std_logic;
    signal mdL0_6_6: std_logic;
    signal mdL0_6_7: std_logic;
    signal dec6_wre27: std_logic;
    signal mdL0_7_0: std_logic;
    signal mdL0_7_1: std_logic;
    signal mdL0_7_2: std_logic;
    signal mdL0_7_3: std_logic;
    signal mdL0_7_4: std_logic;
    signal mdL0_7_5: std_logic;
    signal mdL0_7_6: std_logic;
    signal mdL0_7_7: std_logic;
    signal dec7_wre31: std_logic;

    -- local component declarations
    component DPR16X2B
        port (DI0: in  std_logic; DI1: in  std_logic; WCK: in  std_logic; 
            WRE: in  std_logic; RAD0: in  std_logic; RAD1: in  std_logic; 
            RAD2: in  std_logic; RAD3: in  std_logic; 
            WAD0: in  std_logic; WAD1: in  std_logic; 
            WAD2: in  std_logic; WAD3: in  std_logic; 
            WDO0: out  std_logic; WDO1: out  std_logic; 
            RDO0: out  std_logic; RDO1: out  std_logic);
    end component;
    component FD1P3DX
    -- synopsys translate_off
        generic (GSR : in String);
    -- synopsys translate_on
        port (D: in  std_logic; SP: in  std_logic; CK: in  std_logic; 
            CD: in  std_logic; Q: out  std_logic);
    end component;
    component INV
        port (A: in  std_logic; Z: out  std_logic);
    end component;
    component MUX81
        port (D0: in  std_logic; D1: in  std_logic; D2: in  std_logic; 
            D3: in  std_logic; D4: in  std_logic; D5: in  std_logic; 
            D6: in  std_logic; D7: in  std_logic; SD1: in  std_logic; 
            SD2: in  std_logic; SD3: in  std_logic; Z: out  std_logic);
    end component;
    component ROM16X1
    -- synopsys translate_off
        generic (initval : in String);
    -- synopsys translate_on
        port (AD3: in  std_logic; AD2: in  std_logic; AD1: in  std_logic; 
            AD0: in  std_logic; DO0: out  std_logic);
    end component;
    component VHI
        port (Z: out  std_logic);
    end component;
    attribute initval : string; 
    attribute GSR : string; 
    attribute initval of LUT4_15 : label is "0x8000";
    attribute initval of LUT4_14 : label is "0x8000";
    attribute initval of LUT4_13 : label is "0x8000";
    attribute initval of LUT4_12 : label is "0x8000";
    attribute initval of LUT4_11 : label is "0x8000";
    attribute initval of LUT4_10 : label is "0x8000";
    attribute initval of LUT4_9 : label is "0x8000";
    attribute initval of LUT4_8 : label is "0x8000";
    attribute initval of LUT4_7 : label is "0x8000";
    attribute initval of LUT4_6 : label is "0x8000";
    attribute initval of LUT4_5 : label is "0x8000";
    attribute initval of LUT4_4 : label is "0x8000";
    attribute initval of LUT4_3 : label is "0x8000";
    attribute initval of LUT4_2 : label is "0x8000";
    attribute initval of LUT4_1 : label is "0x8000";
    attribute initval of LUT4_0 : label is "0x8000";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";

begin
    -- component instantiation statements
    INV_2: INV
        port map (A=>WrAddress(4), Z=>waddr4_inv);

    INV_1: INV
        port map (A=>WrAddress(5), Z=>waddr5_inv);

    INV_0: INV
        port map (A=>WrAddress(6), Z=>waddr6_inv);

    LUT4_15: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>waddr4_inv, 
            AD0=>waddr5_inv, DO0=>func_and_inet);

    LUT4_14: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet, AD2=>waddr6_inv, AD1=>scuba_vhi, 
            AD0=>scuba_vhi, DO0=>dec0_wre3);

    LUT4_13: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>WrAddress(4), 
            AD0=>waddr5_inv, DO0=>func_and_inet_1);

    LUT4_12: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet_1, AD2=>waddr6_inv, AD1=>scuba_vhi, 
            AD0=>scuba_vhi, DO0=>dec1_wre7);

    LUT4_11: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>waddr4_inv, 
            AD0=>WrAddress(5), DO0=>func_and_inet_2);

    LUT4_10: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet_2, AD2=>waddr6_inv, AD1=>scuba_vhi, 
            AD0=>scuba_vhi, DO0=>dec2_wre11);

    LUT4_9: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>WrAddress(4), 
            AD0=>WrAddress(5), DO0=>func_and_inet_3);

    LUT4_8: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet_3, AD2=>waddr6_inv, AD1=>scuba_vhi, 
            AD0=>scuba_vhi, DO0=>dec3_wre15);

    LUT4_7: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>waddr4_inv, 
            AD0=>waddr5_inv, DO0=>func_and_inet_4);

    LUT4_6: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet_4, AD2=>WrAddress(6), 
            AD1=>scuba_vhi, AD0=>scuba_vhi, DO0=>dec4_wre19);

    LUT4_5: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>WrAddress(4), 
            AD0=>waddr5_inv, DO0=>func_and_inet_5);

    LUT4_4: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet_5, AD2=>WrAddress(6), 
            AD1=>scuba_vhi, AD0=>scuba_vhi, DO0=>dec5_wre23);

    LUT4_3: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>waddr4_inv, 
            AD0=>WrAddress(5), DO0=>func_and_inet_6);

    LUT4_2: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet_6, AD2=>WrAddress(6), 
            AD1=>scuba_vhi, AD0=>scuba_vhi, DO0=>dec6_wre27);

    LUT4_1: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>WE, AD2=>WrClockEn, AD1=>WrAddress(4), 
            AD0=>WrAddress(5), DO0=>func_and_inet_7);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    LUT4_0: ROM16X1
        -- synopsys translate_off
        generic map (initval=> "0x8000")
        -- synopsys translate_on
        port map (AD3=>func_and_inet_7, AD2=>WrAddress(6), 
            AD1=>scuba_vhi, AD0=>scuba_vhi, DO0=>dec7_wre31);

    FF_7: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout7_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(7));

    FF_6: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout6_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(6));

    FF_5: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout5_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(5));

    FF_4: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout4_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(4));

    FF_3: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout3_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(3));

    FF_2: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout2_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(2));

    FF_1: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout1_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(1));

    FF_0: FD1P3DX
        -- synopsys translate_off
        generic map (GSR=> "ENABLED")
        -- synopsys translate_on
        port map (D=>dataout0_ffin, SP=>RdClockEn, CK=>RdClock, 
            CD=>Reset, Q=>Q(0));

    mux_7: MUX81
        port map (D0=>mdL0_0_0, D1=>mdL0_1_0, D2=>mdL0_2_0, D3=>mdL0_3_0, 
            D4=>mdL0_4_0, D5=>mdL0_5_0, D6=>mdL0_6_0, D7=>mdL0_7_0, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout7_ffin);

    mux_6: MUX81
        port map (D0=>mdL0_0_1, D1=>mdL0_1_1, D2=>mdL0_2_1, D3=>mdL0_3_1, 
            D4=>mdL0_4_1, D5=>mdL0_5_1, D6=>mdL0_6_1, D7=>mdL0_7_1, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout6_ffin);

    mux_5: MUX81
        port map (D0=>mdL0_0_2, D1=>mdL0_1_2, D2=>mdL0_2_2, D3=>mdL0_3_2, 
            D4=>mdL0_4_2, D5=>mdL0_5_2, D6=>mdL0_6_2, D7=>mdL0_7_2, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout5_ffin);

    mux_4: MUX81
        port map (D0=>mdL0_0_3, D1=>mdL0_1_3, D2=>mdL0_2_3, D3=>mdL0_3_3, 
            D4=>mdL0_4_3, D5=>mdL0_5_3, D6=>mdL0_6_3, D7=>mdL0_7_3, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout4_ffin);

    mux_3: MUX81
        port map (D0=>mdL0_0_4, D1=>mdL0_1_4, D2=>mdL0_2_4, D3=>mdL0_3_4, 
            D4=>mdL0_4_4, D5=>mdL0_5_4, D6=>mdL0_6_4, D7=>mdL0_7_4, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout3_ffin);

    mux_2: MUX81
        port map (D0=>mdL0_0_5, D1=>mdL0_1_5, D2=>mdL0_2_5, D3=>mdL0_3_5, 
            D4=>mdL0_4_5, D5=>mdL0_5_5, D6=>mdL0_6_5, D7=>mdL0_7_5, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout2_ffin);

    mux_1: MUX81
        port map (D0=>mdL0_0_6, D1=>mdL0_1_6, D2=>mdL0_2_6, D3=>mdL0_3_6, 
            D4=>mdL0_4_6, D5=>mdL0_5_6, D6=>mdL0_6_6, D7=>mdL0_7_6, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout1_ffin);

    mux_0: MUX81
        port map (D0=>mdL0_0_7, D1=>mdL0_1_7, D2=>mdL0_2_7, D3=>mdL0_3_7, 
            D4=>mdL0_4_7, D5=>mdL0_5_7, D6=>mdL0_6_7, D7=>mdL0_7_7, 
            SD1=>RdAddress(4), SD2=>RdAddress(5), SD3=>RdAddress(6), 
            Z=>dataout0_ffin);

    mem_0_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec0_wre3, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_0_1, RDO1=>mdL0_0_0);

    mem_0_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec0_wre3, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_0_3, RDO1=>mdL0_0_2);

    mem_0_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec0_wre3, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_0_5, RDO1=>mdL0_0_4);

    mem_0_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec0_wre3, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_0_7, RDO1=>mdL0_0_6);

    mem_1_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec1_wre7, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_1_1, RDO1=>mdL0_1_0);

    mem_1_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec1_wre7, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_1_3, RDO1=>mdL0_1_2);

    mem_1_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec1_wre7, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_1_5, RDO1=>mdL0_1_4);

    mem_1_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec1_wre7, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_1_7, RDO1=>mdL0_1_6);

    mem_2_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec2_wre11, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_2_1, RDO1=>mdL0_2_0);

    mem_2_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec2_wre11, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_2_3, RDO1=>mdL0_2_2);

    mem_2_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec2_wre11, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_2_5, RDO1=>mdL0_2_4);

    mem_2_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec2_wre11, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_2_7, RDO1=>mdL0_2_6);

    mem_3_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec3_wre15, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_3_1, RDO1=>mdL0_3_0);

    mem_3_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec3_wre15, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_3_3, RDO1=>mdL0_3_2);

    mem_3_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec3_wre15, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_3_5, RDO1=>mdL0_3_4);

    mem_3_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec3_wre15, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_3_7, RDO1=>mdL0_3_6);

    mem_4_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec4_wre19, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_4_1, RDO1=>mdL0_4_0);

    mem_4_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec4_wre19, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_4_3, RDO1=>mdL0_4_2);

    mem_4_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec4_wre19, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_4_5, RDO1=>mdL0_4_4);

    mem_4_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec4_wre19, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_4_7, RDO1=>mdL0_4_6);

    mem_5_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec5_wre23, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_5_1, RDO1=>mdL0_5_0);

    mem_5_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec5_wre23, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_5_3, RDO1=>mdL0_5_2);

    mem_5_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec5_wre23, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_5_5, RDO1=>mdL0_5_4);

    mem_5_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec5_wre23, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_5_7, RDO1=>mdL0_5_6);

    mem_6_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec6_wre27, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_6_1, RDO1=>mdL0_6_0);

    mem_6_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec6_wre27, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_6_3, RDO1=>mdL0_6_2);

    mem_6_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec6_wre27, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_6_5, RDO1=>mdL0_6_4);

    mem_6_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec6_wre27, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_6_7, RDO1=>mdL0_6_6);

    mem_7_0: DPR16X2B
        port map (DI0=>Data(6), DI1=>Data(7), WCK=>WrClock, 
            WRE=>dec7_wre31, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_7_1, RDO1=>mdL0_7_0);

    mem_7_1: DPR16X2B
        port map (DI0=>Data(4), DI1=>Data(5), WCK=>WrClock, 
            WRE=>dec7_wre31, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_7_3, RDO1=>mdL0_7_2);

    mem_7_2: DPR16X2B
        port map (DI0=>Data(2), DI1=>Data(3), WCK=>WrClock, 
            WRE=>dec7_wre31, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_7_5, RDO1=>mdL0_7_4);

    mem_7_3: DPR16X2B
        port map (DI0=>Data(0), DI1=>Data(1), WCK=>WrClock, 
            WRE=>dec7_wre31, RAD0=>RdAddress(0), RAD1=>RdAddress(1), 
            RAD2=>RdAddress(2), RAD3=>RdAddress(3), WAD0=>WrAddress(0), 
            WAD1=>WrAddress(1), WAD2=>WrAddress(2), WAD3=>WrAddress(3), 
            WDO0=>open, WDO1=>open, RDO0=>mdL0_7_7, RDO1=>mdL0_7_6);

end Structure;

-- synopsys translate_off
library MACHXO;
configuration Structure_CON of DPRAM is
    for Structure
        for all:DPR16X2B use entity MACHXO.DPR16X2B(V); end for;
        for all:FD1P3DX use entity MACHXO.FD1P3DX(V); end for;
        for all:INV use entity MACHXO.INV(V); end for;
        for all:MUX81 use entity MACHXO.MUX81(V); end for;
        for all:ROM16X1 use entity MACHXO.ROM16X1(V); end for;
        for all:VHI use entity MACHXO.VHI(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
