#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jul 20 23:21:43 KST 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim bajie7020_wrapper_func_impl -key {Post-Implementation:sim_1:Functional:bajie7020_wrapper} -tclbatch bajie7020_wrapper.tcl -protoinst "protoinst_files/bd_d278.protoinst" -protoinst "protoinst_files/bd_1229.protoinst" -protoinst "protoinst_files/bajie7020.protoinst" -log simulate.log"
xsim bajie7020_wrapper_func_impl -key {Post-Implementation:sim_1:Functional:bajie7020_wrapper} -tclbatch bajie7020_wrapper.tcl -protoinst "protoinst_files/bd_d278.protoinst" -protoinst "protoinst_files/bd_1229.protoinst" -protoinst "protoinst_files/bajie7020.protoinst" -log simulate.log

