
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_p[1]}]
set_property PACKAGE_PIN T20 [get_ports {ADCD_p[0]}]
set_property PACKAGE_PIN U20 [get_ports {ADCD_n[0]}]
set_property PACKAGE_PIN V20 [get_ports {ADCD_p[1]}]
set_property PACKAGE_PIN W20 [get_ports {ADCD_n[1]}]


set_property IOSTANDARD LVCMOS25 [get_ports {ADC_RESET[0]}]
set_property PACKAGE_PIN P14 [get_ports {ADC_RESET[0]}]

set_property PACKAGE_PIN N20 [get_ports {ADCD_DCLK_clk_p[0]}]
set_property PACKAGE_PIN P20 [get_ports {ADCD_DCLK_clk_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_DCLK_clk_p[0]}]

set_property PACKAGE_PIN N18 [get_ports {ADCD_FCLK_clk_p[0]}]
set_property PACKAGE_PIN P19 [get_ports {ADCD_FCLK_clk_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_FCLK_clk_p[0]}]

set_property PACKAGE_PIN U18 [get_ports {ADC_CLK_clk_p[0]}]
set_property PACKAGE_PIN U19 [get_ports {ADC_CLK_clk_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLK_clk_p[0]}]

set_property PACKAGE_PIN Y18 [get_ports PLL_TXDATA]
set_property IOSTANDARD LVCMOS25 [get_ports PLL_TXDATA]

set_property PACKAGE_PIN G20 [get_ports CAN0_tx]
set_property PACKAGE_PIN G19 [get_ports CAN0_rx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN0_tx]
set_property IOSTANDARD LVCMOS33 [get_ports CAN0_rx]


set_property IOSTANDARD LVCMOS25 [get_ports SPI_0_0_io0_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_0_0_io1_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_0_0_sck_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_0_0_ss1_o]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_0_0_ss2_o]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_0_0_ss_o]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_io0_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_io1_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_sck_io]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_ss1_o]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_ss2_o]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_1_0_ss_o]
set_property PACKAGE_PIN T15 [get_ports SPI_1_0_ss1_o]
set_property PACKAGE_PIN T14 [get_ports SPI_1_0_sck_io]
set_property PACKAGE_PIN V12 [get_ports SPI_1_0_io0_io]
set_property PACKAGE_PIN W13 [get_ports SPI_1_0_io1_io]
set_property PACKAGE_PIN U12 [get_ports SPI_1_0_ss_o]
set_property PACKAGE_PIN T12 [get_ports SPI_1_0_ss2_o]
set_property PACKAGE_PIN T10 [get_ports SPI_0_0_io0_io]
set_property PACKAGE_PIN T11 [get_ports SPI_0_0_io1_io]
set_property PACKAGE_PIN U13 [get_ports SPI_0_0_sck_io]
set_property PACKAGE_PIN V13 [get_ports SPI_0_0_ss1_o]
set_property PACKAGE_PIN W14 [get_ports SPI_0_0_ss2_o]
set_property PACKAGE_PIN Y14 [get_ports SPI_0_0_ss_o]

set_property PACKAGE_PIN T19 [get_ports PLL_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports PLL_CLK]
