#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : bajie7020.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jun 07 12:13:12 +0900 2023
# SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: bajie7020.sh [-help]
# usage: bajie7020.sh [-lib_map_path]
# usage: bajie7020.sh [-noclean_files]
# usage: bajie7020.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'bajie7020.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_11 processing_system7_vip_v1_0_13 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xbip_utils_v3_0_10 axi_utils_v2_0_6 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_bram18k_v3_0_6 mult_gen_v12_0_17 cmpy_v6_0_20 floating_point_v7_0_19 xfft_v9_1_7 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_25 fifo_generator_v13_2_6 axi_data_fifo_v2_1_24 axi_crossbar_v2_1_26 xlconcat_v2_1_4 lib_pkg_v1_0_2 lib_fifo_v1_0_15 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_27 axi_sg_v4_1_14 axi_dma_v7_1_26 xlconstant_v1_1_7 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_25 axis_subset_converter_v1_1_25 axis_data_fifo_v2_0_7 fir_compiler_v7_2_17 axi_protocol_converter_v2_1_25)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "bajie7020.sh - Script generated by export_simulation (Vivado v2021.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2021.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_11 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/63b7/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_processing_system7_0_0/sim/bajie7020_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_rst_ps7_0_200M_0/sim/bajie7020_rst_ps7_0_200M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_17 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/dd36/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cmpy_v6_0_20 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/328f/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_19 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/08ac/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xfft_v9_1_7 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b7d6/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xfft_0_0/sim/bajie7020_xfft_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/e1e6/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8ae1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8ae1/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_24 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fa53/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ac57/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xbar_3/sim/bajie7020_xbar_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xlconcat_0_4/sim/bajie7020_xlconcat_0_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_15 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/a4ed/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_27 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/9b19/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_14 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/bcf6/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_26 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/69a4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axi_dma_1_1/sim/bajie7020_axi_dma_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xlconstant_0_3/sim/bajie7020_xlconstant_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xbar_4/sim/bajie7020_xbar_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axi_dma_0_2/sim/bajie7020_axi_dma_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/d733/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/tdata_bajie7020_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/tuser_bajie7020_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/tstrb_bajie7020_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/tkeep_bajie7020_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/tid_bajie7020_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/tdest_bajie7020_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/tlast_bajie7020_axis_subset_converter_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ba57/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/hdl/top_bajie7020_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_2/sim/bajie7020_axis_subset_converter_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/4852/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_data_fifo_0_0/sim/bajie7020_axis_data_fifo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_proc_sys_reset_0_0/sim/bajie7020_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fir_compiler_v7_2_17 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/cf11/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_fir_compiler_0_0/sim/bajie7020_fir_compiler_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_data_fifo_1_0/sim/bajie7020_axis_data_fifo_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/tdata_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/tuser_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/tstrb_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/tkeep_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/tid_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/tdest_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/tlast_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/hdl/top_bajie7020_axis_subset_converter_1_2.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_2/sim/bajie7020_axis_subset_converter_1_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_rst_ps7_0_133M_0/sim/bajie7020_rst_ps7_0_133M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_rfbdes_0_0/sim/bajie7020_rfbdes_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_firoutmixer_0_0/sim/bajie7020_firoutmixer_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/tdata_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/tuser_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/tstrb_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/tkeep_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/tid_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/tdest_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/tlast_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/hdl/top_bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_3/sim/bajie7020_axis_subset_converter_0_3.v" \
    "$ref_dir/../../../bd/bajie7020/sim/bajie7020.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8fe4/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3007/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_auto_pc_0/sim/bajie7020_auto_pc_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_auto_pc_1/sim/bajie7020_auto_pc_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_auto_pc_2/sim/bajie7020_auto_pc_2.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.bajie7020 xil_defaultlib.glbl -o bajie7020_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./bajie7020_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./bajie7020.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key bajie7020_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc bajie7020_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./bajie7020.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: bajie7020.sh [-help]\n\
Usage: bajie7020.sh [-lib_map_path]\n\
Usage: bajie7020.sh [-reset_run]\n\
Usage: bajie7020.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
