#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : bajie7020.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Jul 16 18:00:55 KST 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# Tool Version Limit: 2022.04 
#
# usage: bajie7020.sh [-help]
# usage: bajie7020.sh [-lib_map_path]
# usage: bajie7020.sh [-noclean_files]
# usage: bajie7020.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'bajie7020.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_12 processing_system7_vip_v1_0_14 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xlconcat_v2_1_4 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_8 axis_register_slice_v1_1_26 axis_subset_converter_v1_1_26 xbip_utils_v3_0_10 axi_utils_v2_0_6 fir_compiler_v7_2_18 lib_pkg_v1_0_2 fifo_generator_v13_2_7 lib_fifo_v1_0_16 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_28 axi_sg_v4_1_15 axi_dma_v7_1_27 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_26 axi_data_fifo_v2_1_25 axi_crossbar_v2_1_27 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 cmpy_v6_0_21 floating_point_v7_0_20 xfft_v9_1_8 xlconstant_v1_1_7 gigantic_mux axi_protocol_converter_v2_1_26)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "bajie7020.sh - Script generated by export_simulation (Vivado v2022.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_12 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1033/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_14 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_processing_system7_0_0_1/sim/bajie7020_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_rst_ps7_0_160M_0/sim/bajie7020_rst_ps7_0_160M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xlconcat_0_0/sim/bajie7020_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_proc_sys_reset_rfb_fclk_0/sim/bajie7020_proc_sys_reset_rfb_fclk_0.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_rst_ps7_0_200M_0_1/sim/bajie7020_rst_ps7_0_200M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_firoutmixer_0_0_1/sim/bajie7020_firoutmixer_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/0bd2/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_data_fifo_0_0_1/sim/bajie7020_axis_data_fifo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/aca3/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/tdata_bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/tuser_bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/tstrb_bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/tkeep_bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/tid_bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/tdest_bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/tlast_bajie7020_axis_subset_converter_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1676/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/hdl/top_bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_1_0/sim/bajie7020_axis_subset_converter_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_data_fifo_1_0_1/sim/bajie7020_axis_data_fifo_1_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/tdata_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/tuser_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/tstrb_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/tkeep_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/tid_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/tdest_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/tlast_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/hdl/top_bajie7020_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_0/sim/bajie7020_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fir_compiler_v7_2_18 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/d172/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_fir_compiler_0_0_1/sim/bajie7020_fir_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_family_support.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_family.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/proc_common_v3_30_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/interrupt_control_v2_01_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_interrupt_control.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/bajie7020_xadc_wiz_0_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/bajie7020_xadc_wiz_0_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/bajie7020_xadc_wiz_0_0_axi_xadc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xadc_wiz_0_0_1/bajie7020_xadc_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_28 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1bb8/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/751a/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_27 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/7b0b/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_rfb_axi_dma_0/sim/bajie7020_rfb_axi_dma_0.vhd" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xfft_axi_dma_0/sim/bajie7020_xfft_axi_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/0a3f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_25 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5390/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/3fa0/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xbar_0/sim/bajie7020_xbar_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xbar_1/sim/bajie7020_xbar_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/tdata_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/tuser_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/tstrb_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/tkeep_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/tid_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/tdest_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/tlast_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/hdl/top_bajie7020_axis_subset_converter_0_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_axis_subset_converter_0_1/sim/bajie7020_axis_subset_converter_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cmpy_v6_0_21 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b7d0/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_20 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b8e/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xfft_v9_1_8 $vhdlan_opts \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/102e/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xfft_0_0_1/sim/bajie7020_xfft_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_xlconstant_32_0_0/sim/bajie7020_xlconstant_32_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_system_ila_0_0/bd_0/ip/ip_0/sim/bd_1229_ila_lib_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gigantic_mux $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/e87a/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_system_ila_0_0/bd_0/ip/ip_1/bd_1229_g_inst_0_gigantic_mux.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_system_ila_0_0/bd_0/ip/ip_1/sim/bd_1229_g_inst_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_system_ila_0_0/bd_0/sim/bd_1229.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_system_ila_0_0/sim/bajie7020_system_ila_0_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_rfbdes_0_0_1/sim/bajie7020_rfbdes_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/90c8/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/5765/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Bajie7020.gen/sources_1/bd/bajie7020/ipshared/fd26/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2022.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_auto_pc_0/sim/bajie7020_auto_pc_0.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_auto_pc_1/sim/bajie7020_auto_pc_1.v" \
    "$ref_dir/../../../bd/bajie7020/ip/bajie7020_auto_pc_2/sim/bajie7020_auto_pc_2.v" \
    "$ref_dir/../../../bd/bajie7020/sim/bajie7020.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.bajie7020 xil_defaultlib.glbl -o bajie7020_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./bajie7020_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./bajie7020.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/penta/Documents/BikeRadar/Bajie7020/Bajie7020.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key bajie7020_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc bajie7020_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./bajie7020.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: bajie7020.sh [-help]\n\
Usage: bajie7020.sh [-lib_map_path]\n\
Usage: bajie7020.sh [-reset_run]\n\
Usage: bajie7020.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
