set_property IOSTANDARD LVDS_25 [get_ports {ADC_DCLK_clk_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_FCLK_clk_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN R13 [get_ports {ADC_DCLK_clk_p[0]}]
set_property PACKAGE_PIN R14 [get_ports {ADC_DCLK_clk_n[0]}]
set_property PACKAGE_PIN P14 [get_ports {ADC_FCLK_clk_p[0]}]
set_property PACKAGE_PIN P15 [get_ports {ADC_FCLK_clk_n[0]}]
set_property PACKAGE_PIN R9 [get_ports {ADC_D_p[0]}]
set_property PACKAGE_PIN R10 [get_ports {ADC_D_n[0]}]
set_property PACKAGE_PIN R11 [get_ports {ADC_D_p[1]}]
set_property PACKAGE_PIN R12 [get_ports {ADC_D_n[1]}]
set_property PACKAGE_PIN N14 [get_ports {ADC_D_p[2]}]
set_property PACKAGE_PIN N15 [get_ports {ADC_D_n[2]}]
set_property PACKAGE_PIN M14 [get_ports {ADC_D_p[3]}]
set_property PACKAGE_PIN M15 [get_ports {ADC_D_n[3]}]

set_property PACKAGE_PIN B2 [get_ports reset]

set_property IOSTANDARD TMDS_33 [get_ports HDMI_TX_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_TX_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {HDMI_TX_data_n[0]}]

set_property PACKAGE_PIN F4 [get_ports {HyperBus_0_hb_dq[7]}]
set_property PACKAGE_PIN A3 [get_ports HyperBus_0_hb_cs_n]
set_property PACKAGE_PIN E3 [get_ports {HyperBus_0_hb_dq[6]}]
set_property PACKAGE_PIN D4 [get_ports {HyperBus_0_hb_dq[1]}]
set_property PACKAGE_PIN E2 [get_ports {HyperBus_0_hb_dq[5]}]
set_property PACKAGE_PIN C5 [get_ports HyperBus_0_hb_ck_p]
set_property PACKAGE_PIN B3 [get_ports HyperBus_0_hb_rwds]
set_property PACKAGE_PIN C1 [get_ports {HyperBus_0_hb_dq[3]}]
set_property PACKAGE_PIN D3 [get_ports {HyperBus_0_hb_dq[0]}]
set_property PACKAGE_PIN B1 [get_ports {HyperBus_0_hb_dq[2]}]
set_property PACKAGE_PIN B5 [get_ports HyperBus_0_hb_ck_n]
set_property PACKAGE_PIN A2 [get_ports HyperBus_0_hb_reset_n]
set_property PACKAGE_PIN D1 [get_ports {HyperBus_0_hb_dq[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HyperBus_0_hb_dq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports HyperBus_0_hb_ck_n]
set_property IOSTANDARD LVCMOS33 [get_ports HyperBus_0_hb_ck_p]
set_property IOSTANDARD LVCMOS33 [get_ports HyperBus_0_hb_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports HyperBus_0_hb_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports HyperBus_0_hb_rwds]



create_clock -period 3.472 -name {ADC_DCLK_clk_p[0]} -waveform {0.000 1.736} [get_ports {ADC_DCLK_clk_p[0]}]
create_clock -period 20.833 -name {ADC_FCLK_clk_p[0]} -waveform {0.000 10.416} [get_ports {ADC_FCLK_clk_p[0]}]


create_interface HDMI_TX
set_property INTERFACE HDMI_TX [get_ports { HDMI_TX_data_p[2] HDMI_TX_data_p[1] HDMI_TX_data_p[0] HDMI_TX_data_n[2] HDMI_TX_data_n[1] HDMI_TX_data_n[0] HDMI_CEC[0] HDMI_HPD[0] HDMI_LSOE[0] HDMI_TX_clk_p HDMI_TX_clk_n }]
set_property PACKAGE_PIN P1 [get_ports {HDMI_TX_data_p[0]}]
set_property PACKAGE_PIN N1 [get_ports {HDMI_TX_data_n[0]}]
set_property PACKAGE_PIN M1 [get_ports HDMI_TX_clk_p]
set_property PACKAGE_PIN L1 [get_ports HDMI_TX_clk_n]
set_property PACKAGE_PIN R2 [get_ports {HDMI_TX_data_p[1]}]
set_property PACKAGE_PIN P2 [get_ports {HDMI_TX_data_n[1]}]
set_property PACKAGE_PIN R4 [get_ports {HDMI_TX_data_p[2]}]
set_property PACKAGE_PIN R3 [get_ports {HDMI_TX_data_n[2]}]


set_property CONFIG_VOLTAGE 2.5 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design]
set_property BITSTREAM.CONFIG.PERSIST YES [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 40 [current_design]
set_property CONFIG_MODE SPIx1 [current_design]
set_property BITSTREAM.STARTUP.STARTUPCLK CCLK [current_design]

set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports HDMI_IIC_scl]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_IIC_sda_tri_io]
set_property PULLUP true [get_ports HDMI_IIC_sda_tri_io]
set_property DRIVE 8 [get_ports HDMI_IIC_sda_tri_io]
create_clock -period 25000.000 -name HDMI_IIC_scl -waveform {0.000 12500.000} [get_ports HDMI_IIC_scl]
create_interface HDMI_IIC -parent HDMI_TX
set_property INTERFACE HDMI_IIC [get_ports { HDMI_IIC_scl HDMI_IIC_sda_tri_io }]

set_property IOSTANDARD LVCMOS25 [get_ports {SPI_SS_N_MASTER[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SPI_SS_N_MASTER[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SPI_SS_N_MASTER[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SPI_SS_N_MASTER[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SPI_SS_N_MASTER[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_MISO_MASTER]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_MOSI_MASTER]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_SCLK_MASTER]
set_property PACKAGE_PIN P6 [get_ports {SPI_SS_N_MASTER[4]}]
create_interface SPI
set_property INTERFACE SPI [get_ports { SPI_SS_N_MASTER[4] SPI_SS_N_MASTER[3] SPI_SS_N_MASTER[2] SPI_SS_N_MASTER[1] SPI_SS_N_MASTER[0] SPI_MISO_MASTER SPI_MOSI_MASTER SPI_SCLK_MASTER }]
create_interface ADC
set_property INTERFACE ADC [get_ports { ADC_D_p[3] ADC_D_p[2] ADC_D_p[1] ADC_D_p[0] ADC_D_n[3] ADC_D_n[2] ADC_D_n[1] ADC_D_n[0] }]

set_property IOSTANDARD LVCMOS25 [get_ports {ADC_RESET[0]}]
set_property PACKAGE_PIN L14 [get_ports {ADC_RESET[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PLL_RAMPCLK[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PLL_RAMPDIR[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports PLL_MUXIN]
set_property PACKAGE_PIN P10 [get_ports PLL_MUXIN]
set_property IOSTANDARD LVCMOS25 [get_ports {PA_EN[0]}]
set_property PACKAGE_PIN N6 [get_ports {PA_EN[0]}]
set_property IOSTANDARD LVDS_25 [get_ports CLK_48M_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports CLK_48M_clk_n]
set_property PACKAGE_PIN H1 [get_ports CLK_48M_clk_p]
set_property PACKAGE_PIN G1 [get_ports CLK_48M_clk_n]
create_interface PLL
set_property INTERFACE PLL [get_ports { PLL_RAMPCLK[0] PLL_RAMPDIR[0] PLL_MUXIN }]
create_interface PA
set_property INTERFACE PA [get_ports { PA_EN[0] }]






set_property PACKAGE_PIN R5 [get_ports {PLL_RAMPCLK[0]}]
set_property PACKAGE_PIN R6 [get_ports {PLL_RAMPDIR[0]}]

set_property PACKAGE_PIN L13 [get_ports {SPI_SS_N_MASTER[3]}]
set_property PACKAGE_PIN M13 [get_ports SPI_MISO_MASTER]
set_property PACKAGE_PIN P11 [get_ports SPI_MOSI_MASTER]
set_property PACKAGE_PIN P12 [get_ports SPI_SCLK_MASTER]
set_property PACKAGE_PIN N7 [get_ports {SPI_SS_N_MASTER[2]}]
set_property PACKAGE_PIN N10 [get_ports {SPI_SS_N_MASTER[0]}]



set_property PACKAGE_PIN N9 [get_ports {SPI_SS_N_MASTER[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LNA_P[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LNA_P[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LNA_P[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LNA_P[0]}]
set_property PACKAGE_PIN E1 [get_ports {LNA_P[0]}]
set_property PACKAGE_PIN F1 [get_ports {LNA_P[1]}]
set_property PACKAGE_PIN F2 [get_ports {LNA_P[2]}]
set_property PACKAGE_PIN F3 [get_ports {LNA_P[3]}]

set_property PACKAGE_PIN B4 [get_ports {XS_LED1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XS_LED1[0]}]
set_property DRIVE 12 [get_ports {XS_LED1[0]}]
set_property PACKAGE_PIN A4 [get_ports XS_SW2]
set_property IOSTANDARD LVCMOS33 [get_ports XS_SW2]
set_property DRIVE 8 [get_ports {PA_EN[0]}]
set_property BITSTREAM.GENERAL.DEBUGBITSTREAM YES [current_design]

set_property PACKAGE_PIN M7 [get_ports {PLL_CE[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PLL_CE[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_CEC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_HPD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_LSOE[0]}]
set_property PACKAGE_PIN N2 [get_ports HDMI_IIC_scl]
set_property PACKAGE_PIN M3 [get_ports HDMI_IIC_sda_tri_io]
set_property PACKAGE_PIN M2 [get_ports {HDMI_CEC[0]}]
set_property PACKAGE_PIN N3 [get_ports {HDMI_HPD[0]}]
set_property PACKAGE_PIN P3 [get_ports {HDMI_LSOE[0]}]
set_property DRIVE 8 [get_ports {HDMI_CEC[0]}]
set_property DRIVE 8 [get_ports {HDMI_HPD[0]}]
set_property DRIVE 8 [get_ports {HDMI_LSOE[0]}]
set_property DRIVE 8 [get_ports {ADC_RESET[0]}]
set_property DRIVE 8 [get_ports {SPI_SS_N_MASTER[4]}]
set_property DRIVE 8 [get_ports {SPI_SS_N_MASTER[3]}]
set_property DRIVE 8 [get_ports {SPI_SS_N_MASTER[2]}]
set_property DRIVE 8 [get_ports {SPI_SS_N_MASTER[1]}]
set_property DRIVE 8 [get_ports {SPI_SS_N_MASTER[0]}]
set_property SLEW SLOW [get_ports {SPI_SS_N_MASTER[4]}]
set_property SLEW SLOW [get_ports {SPI_SS_N_MASTER[3]}]
set_property SLEW SLOW [get_ports {SPI_SS_N_MASTER[2]}]
set_property SLEW SLOW [get_ports {SPI_SS_N_MASTER[1]}]
set_property SLEW SLOW [get_ports {SPI_SS_N_MASTER[0]}]
set_property DRIVE 8 [get_ports {PLL_CE[0]}]

set_property OFFCHIP_TERM NONE [get_ports SPI_MOSI_MASTER]
set_property OFFCHIP_TERM NONE [get_ports SPI_SCLK_MASTER]
set_property OFFCHIP_TERM NONE [get_ports LNA_P[3]]
set_property OFFCHIP_TERM NONE [get_ports LNA_P[2]]
set_property OFFCHIP_TERM NONE [get_ports LNA_P[1]]
set_property OFFCHIP_TERM NONE [get_ports LNA_P[0]]
set_property OFFCHIP_TERM NONE [get_ports PLL_RAMPCLK[0]]
set_property OFFCHIP_TERM NONE [get_ports PLL_RAMPDIR[0]]
set_property OFFCHIP_TERM NONE [get_ports XS_LED1[0]]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_D_p[0]}]
